---
name: "YAML Lint Workflow"

on:  # yamllint disable-line rule:truthy
  # Makes it reusable; called by other workflows
  workflow_call:

jobs:
  yamllint:
    runs-on: "ubuntu-latest"
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@v6"
      - name: "Set up Python 3.12"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.12"
      - name: "Cache PIP Dependencies"
        uses: "actions/cache@v4"
        with:
          path: ~/.cache/pip
          key: |
            ${{ runner.os }}-pip-3.12-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.12-
            ${{ runner.os }}-pip-
      - name: "Install yamllint"
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: "Check yamllint Version"
        run: |
          yamllint --version
      - name: "Lint with yamllint"
        run: |
          yamllint .
